services:

  tpbmo_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpbmo_db
      MYSQL_USER: tpbmo
      MYSQL_PASSWORD: tpbmo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: tpbmo_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - tpbmo_db

volumes:
  mysql_data:
