package model;

import java.time.LocalDateTime;

public class DemandeParole {
    private int id;
    private int personneId;
    private int reunionId;
    private LocalDateTime heureDemande;
    public enum StatutDemande {EN_ATTENTE, ACCORDEE, REFUSEE, TERMINEE}
    private StatutDemande statutDemande;

    // Constructor for creating an object from database data
    public DemandeParole(int id, int personneId, int reunionId, LocalDateTime heureDemande, StatutDemande statutDemande) {
        this.id = id;
        this.personneId = personneId;
        this.reunionId = reunionId;
        this.heureDemande = heureDemande; // Use the provided heureDemande
        this.statutDemande = statutDemande;
    }

    // Constructor for creating a new request (usually ID is auto-generated by DB)
    // And heureDemande is set by DB default or NOW()
    public DemandeParole(int personneId, int reunionId, StatutDemande statutDemande) {
        this.personneId = personneId;
        this.reunionId = reunionId;
        this.statutDemande = statutDemande;
        // this.heureDemande will be set by the database or upon retrieval
    }


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getPersonneId() {
        return personneId;
    }

    public void setPersonneId(int personneId) {
        this.personneId = personneId;
    }

    public int getReunionId() {
        return reunionId;
    }

    public void setReunionId(int reunionId) {
        this.reunionId = reunionId;
    }

    public LocalDateTime getHeureDemande() {
        return heureDemande;
    }

    public void setHeureDemande(LocalDateTime heureDemande) {
        this.heureDemande = heureDemande;
    }

    public StatutDemande getStatutDemande() {
        return statutDemande;
    }

    public void setStatutDemande(StatutDemande statutDemande) {
        this.statutDemande = statutDemande;
    }
}