package model;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class Reunion {
    private int id;
    private String nom;
    private String sujet;
    private String agenda;
    private LocalDateTime debut; // Changed to LocalDateTime
    private int duree;
    private String meetingCode; // New field

    public Reunion(String nom, String sujet, String agenda, LocalDateTime debut, int duree, Type type, int organisateurId, Integer animateurId) {
        this.nom = nom; 
        this.sujet = sujet; 
        this.agenda = agenda; // Corrected parameter name usage
        this.debut = debut; // Assign LocalDateTime directly
        this.duree = duree;
        this.type = type; // Corrected parameter name usage
        this.idOrganisateur = idOrganisateur;
        this.idOrganisateur = organisateurId; // Corrected parameter name usage
        // Handle null Integer for primitive int idAnimateur
        this.idAnimateur = (animateurId == null) ? 0 : animateurId.intValue();
        this.meetingCode = null; // Generated by server
    }

    public enum Type {STANDARD, PRIVEE, DEMOCRATIQUE}
    private Type type;
    private int idOrganisateur;
    private int idAnimateur; // This is int

    // Updated constructor to include meetingCode
    public Reunion(int id, String nom, String sujet, String agenda, LocalDateTime debut, int duree, Type type, int idOrganisateur, int idAnimateur, String meetingCode) {
        this.id = id;
        this.nom = nom;
        this.sujet = sujet;
        this.agenda = agenda;
        this.debut = debut; 
        this.duree = duree;
        this.type = type;
        this.idOrganisateur = idOrganisateur;
        this.idAnimateur = idAnimateur;
        this.meetingCode = meetingCode;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getSujet() {
        return sujet;
    }

    public void setSujet(String sujet) {
        this.sujet = sujet;
    }

    public String getAgenda() {
        return agenda;
    }

    public void setAgenda(String agenda) {
        this.agenda = agenda;
    }

    public LocalDateTime getDebut() { // Changed return type
        return debut;
    }

    public void setDebut(LocalDateTime debut) { // Changed parameter type
        this.debut = debut;
    }

    public int getDuree() {
        return duree;
    }

    public void setDuree(int duree) {
        this.duree = duree;
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public int getIdOrganisateur() {
        return idOrganisateur;
    }

    public void setIdOrganisateur(int idOrganisateur) {
        this.idOrganisateur = idOrganisateur;
    }

    public int getIdAnimateur() {
        return idAnimateur;
    }

    public void setIdAnimateur(int idAnimateur) {
        this.idAnimateur = idAnimateur;
    }

    public String getMeetingCode() {
        return meetingCode;
    }

    public void setMeetingCode(String meetingCode) {
        this.meetingCode = meetingCode;
    }

    @Override
    public String toString() {
        return "Reunion{" +
                "id=" + id +
                ", nom='" + nom + '\'' +
                ", sujet='" + sujet + '\'' +
                ", agenda='" + agenda + '\'' +
                ", debut=" + debut +
                ", duree=" + duree +
                ", type=" + type +
                ", idOrganisateur=" + idOrganisateur +
                ", idAnimateur=" + idAnimateur +
                ", meetingCode='" + meetingCode + '\'' +
                '}';
    }
}